---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-stars.fullname" . }}
  labels:
    {{- include "github-stars.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "github-stars.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "github-stars.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.claimName }}
      containers:
      - name: github-stars
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args:
        - '-directory=/data'
        - '-user={{ .Values.server.user }}'
        - '-github.token=$(github.token)'  
        - '-github.webhook.secret=$(github.webhook.secret)'
        - '-slack.webhook=$(slack.webHook)'
        {{- with .Values.deployment.args }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ .Values.server.credentials | default (include "github-stars.fullname" .) }}
        ports:
        - containerPort: 8080
        - containerPort: 9100
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
        resources:
{{- toYaml .Values.deployment.resources | nindent 10 }}
        volumeMounts:
          - name: data
            mountPath: /data
