apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "covid19.fullname" . }}-handler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "covid19.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "covid19.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Chart.Name }}
        {{- include "covid19.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ include "covid19.getConfigMap" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.handler.image.repository }}:{{ .Values.handler.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.handler.image.pullPolicy }}
          args:
            - --config=/etc/covid19/covid19.yml
          envFrom:
            - secretRef:
                name: {{ include "covid19.getSecret" . }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.handler.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/covid19
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
