{
 "title": "Energy",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(proteus_battery_flow,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Grid",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(proteus_grid_current_power{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(proteus_solar_current_power{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(proteus_battery_flow{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(proteus_grid_current_power{namespace=\"$namespace\"})+1000*sum(proteus_battery_flow{namespace=\"$namespace\"})+sum(proteus_solar_current_power{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Tariff",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_grid_active_tariff{namespace=~\"^$namespace$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_battery_load{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(proteus_grid_current_power{namespace=\"$namespace\"})",
     "legendFormat": "grid"
    },
    {
     "expr": "avg(proteus_solar_current_power{namespace=\"$namespace\"})",
     "legendFormat": "solar"
    },
    {
     "expr": "avg(proteus_battery_flow{namespace=\"$namespace\"})*1000",
     "legendFormat": "battery"
    },
    {
     "expr": "avg(proteus_grid_current_power{namespace=\"$namespace\"})+avg(proteus_solar_current_power{namespace=\"$namespace\"})+avg(proteus_battery_flow{namespace=\"$namespace\"})*1000",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Flow (alt)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(proteus_grid_current_power{namespace=\"$namespace\"})",
     "legendFormat": "grid"
    },
    {
     "expr": "avg(proteus_solar_current_power{namespace=\"$namespace\"})",
     "legendFormat": "solar"
    },
    {
     "expr": "avg(proteus_battery_flow{namespace=\"$namespace\"})*1000",
     "legendFormat": "battery"
    },
    {
     "expr": "avg(proteus_grid_current_power{namespace=\"$namespace\"})+avg(proteus_solar_current_power{namespace=\"$namespace\"})+avg(proteus_battery_flow{namespace=\"$namespace\"})*1000",
     "legendFormat": "load"
    }
   ]
  }
 ]
}
{
 "title": "Heating",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(proteus_heating_outside_temperature,namespace)"
    }
   },
   {
    "name": "room",
    "label": "Room",
    "query": {
     "query": "label_values(proteus_heating_zone_temperature,zone)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Outside temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_heating_outside_temperature{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solar intensity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_heating_solar_intensity{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All rooms",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(proteus_heating_zone_temperature{zone=~\"^$room$\",namespace=~\"^$namespace$\"}) by (zone)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Heating percentage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_heating_zone_heating{zone=~\"^$room$\",namespace=~\"^$namespace$\"}) by (zone)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Heating mode",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_heating_zone_manual{zone=~\"^$room$\",namespace=~\"^$namespace$\"}) by (zone)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Mobile devices",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_heating_user_state{namespace=~\"^$namespace$\"}) by (user)",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (proteus_heating_weather_state{namespace=~\"^$namespace$\"}) by (state) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (proteus_heating_weather_state{namespace=~\"^$namespace$\"}) by (state) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proteus_heating_home_state{namespace=~\"^$namespace$\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (proteus_heating_home_state{namespace=~\"^$namespace$\"} == 1) by (state)",
     "legendFormat": "{{proteus_tado_weather}}"
    }
   ]
  },
  { "title": "room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "room" },
  {
   "title": "Heating - $room",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(proteus_heating_zone_target_temperature{zone=~\"^$room$\",namespace=~\"^$namespace$\"}) by (zone)",
     "legendFormat": "Target"
    },
    {
     "expr": "avg(proteus_heating_zone_temperature{zone=~\"^$room$\",namespace=~\"^$namespace$\"}) by (zone)",
     "legendFormat": "Temperature"
    },
    {
     "expr": "avg(proteus_heating_zone_heating{zone=~\"^$room$\",namespace=~\"^$namespace$\"}) by (zone)",
     "legendFormat": "Heating"
    }
   ]
  },
  {
   "title": "Humidity - $room",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(proteus_heating_zone_humidity{zone=~\"^$room$\",namespace=~\"^$namespace$\"})",
     "legendFormat": "Humidity"
    },
    {
     "expr": "avg(proteus_heating_zone_open_window_remaining{zone=\"$room\",namespace=~\"^$namespace$\"})",
     "legendFormat": "Open Window"
    }
   ]
  },
  {
   "title": "Devices status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(proteus_heating_device_battery_state{zone=~\"^$room$\"})",
     "legendFormat": "Battery"
    },
    {
     "expr": "avg(proteus_heating_device_connection_state{zone=~\"^$room$\"})",
     "legendFormat": "Connection"
    }
   ]
  }
 ]
}
{
 "title": "Internal - go metrics",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_goroutines{app_kubernetes_io_name=\"proteus\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{namespace=\"$namespace\",container!=\"\"}[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (go_goroutines{namespace=\"$namespace\"}) by (app_kubernetes_io_component)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum (rate(go_memstats_mallocs_total{namespace=\"$namespace\"}[$__rate_interval])) by (app_kubernetes_io_component)",
     "legendFormat": "alloc - {{app_kubernetes_io_component}}"
    },
    {
     "expr": "sum (rate(go_memstats_frees_total{namespace=\"$namespace\"}[$__rate_interval])) by (app_kubernetes_io_component)",
     "legendFormat": "free - {{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (go_gc_duration_seconds_sum{namespace=\"$namespace\"} / go_gc_duration_seconds_count{namespace=~\"$namespace\"}) by (app_kubernetes_io_component)",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  }
 ]
}
{
 "title": "Internal - scrape clients",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(proteus_scraper_http_requests_total,namespace)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(proteus_scraper_http_request_duration_seconds_bucket{namespace=\"$namespace\"},application)"
    }
   }
  ]
 },
 "panels": [
  { "title": "client requests - $application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "application" },
  {
   "title": "Responses",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(proteus_scraper_http_requests_total{namespace=~\"^$namespace$\",application=~\"^$application$\"}) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg (rate(proteus_scraper_http_requests_total{namespace=~\"^$namespace$\",application=~\"^$application$\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(proteus_scraper_http_request_duration_seconds_bucket{namespace=\"$namespace\", application=~\"^$application$\"}[$__rate_interval])) by (application,le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Solar Panels",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(proteus_solar_current_power,namespace)"
    }
   },
   {
    "name": "site",
    "query": {
     "query": "label_values(proteus_solar_current_power,site)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Output",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_solar_current_power{namespace=~\"^$namespace$\", site=~\"^$site\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_solar_day_energy{namespace=~\"^$namespace$\", site=~\"^$site\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Month",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_solar_month_energy{namespace=~\"^$namespace$\", site=~\"^$site\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Year",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proteus_solar_year_energy{namespace=~\"^$namespace$\", site=~\"^$site\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(proteus_solar_current_power{namespace=~\"^$namespace$\", site=~\"^$site$\"})",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg (proteus_solar_inverter_temperature{namespace=~\"^$namespace\", site=~\"^$site$\"})"
    }
   ]
  },
  {
   "title": "Output (V, A)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg (proteus_solar_inverter_ac_voltage{namespace=~\"^$namespace\", site=~\"^$site$\"})",
     "legendFormat": "AC voltage"
    },
    {
     "expr": "avg (proteus_solar_inverter_dc_voltage{namespace=~\"^$namespace\", site=~\"^$site$\"})",
     "legendFormat": "DC voltage"
    },
    {
     "expr": "avg (proteus_solar_inverter_ac_current{namespace=~\"^$namespace\", site=~\"^$site$\"})",
     "legendFormat": "AC current"
    }
   ]
  }
 ]
}