{
 "title": "homewizard",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(proteus_homewizard_current_power,namespace)"
    }
   },
   {
    "name": "battery",
    "query": {
     "query": "label_values(proteus_battery_capacity{namespace=\"$namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Power Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(proteus_homewizard_current_power{namespace=~\"^$namespace$\"}) < 0",
     "legendFormat": "out"
    },
    {
     "expr": "avg(proteus_homewizard_current_power{namespace=~\"^$namespace$\"}) > 0",
     "legendFormat": "in"
    },
    {
     "expr": "avg(proteus_homewizard_peak_power{namespace=~\"^$namespace$\"})",
     "legendFormat": "peak"
    },
    {
     "expr": "avg(-proteus_solaredge_current_power{namespace=~\"^$namespace$\"} offset -450s)",
     "legendFormat": "solar"
    }
   ]
  },
  {
   "title": "Net Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(proteus_homewizard_current_power{namespace=~\"^$namespace$\"}) + avg(proteus_solaredge_current_power{namespace=~\"^$namespace$\"} offset -450s)",
     "legendFormat": "consumption"
    }
   ]
  },
  { "title": "battery: $battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "battery" },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "avg(proteus_battery_capacity{name=~\"^$battery$\", namespace=~\"^$namespace$\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "avg(proteus_battery_charge{name=~\"^$battery$\", namespace=~\"^$namespace$\"})",
     "legendFormat": "charge"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(proteus_battery_grid{name=~\"^$battery$\", namespace=~\"^$namespace$\"})",
     "legendFormat": "net"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(delta(proteus_battery_charge{namespace=~\"^$namespace$\", name=~\"^$battery$\"}[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}