{
 "title": "Solar Panels",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(proteus_solaredge_current_power,namespace)"
    }
   },
   {
    "name": "site",
    "query": {
     "query": "label_values(proteus_solaredge_current_power,site)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Output",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(proteus_solaredge_current_power{namespace=~\"^$namespace\", site=~\"^$site$\"})"
    }
   ]
  },
  {
   "title": "Today",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg (proteus_solaredge_day_energy{namespace=~\"^$namespace\", site=~\"^$site$\"})"
    }
   ]
  },
  {
   "title": "Month",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg (proteus_solaredge_month_energy{namespace=~\"^$namespace\", site=~\"^$site$\"})"
    }
   ]
  },
  {
   "title": "Year",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg (proteus_solaredge_year_energy{namespace=~\"^$namespace\", site=~\"^$site$\"})"
    }
   ]
  },
  {
   "title": "Output (W)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg  (proteus_solaredge_current_power{namespace=~\"^$namespace\", site=~\"^$site$\"})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg (proteus_solaredge_inverter_temperature{namespace=~\"^$namespace\", site=~\"^$site$\"})"
    }
   ]
  },
  {
   "title": "Output (V, A)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg (proteus_solaredge_inverter_ac_voltage{namespace=~\"^$namespace\", site=~\"^$site$\"})",
     "legendFormat": "AC voltage"
    },
    {
     "expr": "avg (proteus_solaredge_inverter_dc_voltage{namespace=~\"^$namespace\", site=~\"^$site$\"})",
     "legendFormat": "DC voltage"
    },
    {
     "expr": "avg (proteus_solaredge_inverter_ac_current{namespace=~\"^$namespace\", site=~\"^$site$\"})",
     "legendFormat": "AC current"
    }
   ]
  }
 ]
}