{
 "title": "tado internals",
 "tags": [ "grope" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "zone",
    "query": {
     "query": "label_values(proteus_tado_zone_heating_percentage,zone_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"proteus-tado-controller\"}"
    }
   ]
  },
  {
   "title": "home rules",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"proteus-tado-controller\"} |= `` | json | type = `home`"
    }
   ]
  },
  {
   "title": "zone rules: $zone",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"proteus-tado-controller\"} |= `` | json | zone =~ `^$zone$`"
    }
   ]
  }
 ]
}