apiVersion: v1
kind: ConfigMap
metadata:
  name: proteus-config
  labels:
    {{- include "proteus.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $config := .Values.config | deepCopy }}
    {{- if and $config.climate $config.climate.controller (not (or .Values.rules.configMap .Values.rules.secret)) }}
    {{- $_ := unset $config.climate.controller "rules" }}
    {{- end }}
    {{- $config | toYaml | nindent 4 }}
---
