---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "proteus.fullname" . }}-redis
  labels:
    {{- include "proteus.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "proteus.fullname" . }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "proteus.fullname" . }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: proteus-redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          args:
            - --save
            - ""
            - --appendonly
            - "no"
            - --requirepass $(REDIS_PASSWORD)
          envFrom:
            - secretRef:
                name: {{ .Values.redis.credentials }}
          ports:
            - containerPort: 6379