{{- if .Values.watchdog.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "proteus.fullname" . }}-watchdog
  labels:
    {{- include "proteus.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "proteus.fullname" . }}
      app.kubernetes.io/component: watchdog
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
        {{- with .Values.watchdog.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ template "proteus.fullname" . }}
        app.kubernetes.io/component: watchdog
        {{- with .Values.watchdog.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Always
      {{- with .Values.watchdog.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.watchdog.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.watchdog.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: watchdog
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - watchdog
            - --redis.password=$(REDIS_PASSWORD)
            - --alertmanager={{ .Values.watchdog.alertmanager }}
            - --interval={{ .Values.watchdog.interval | default "5m" }}
            {{- with .Values.watchdog.channels}}
            - --channels={{ . | quote }}
            {{- end }}
            {{- with .Values.watchdog.args }}
            {{- toYaml . | nindent 12 }}
            {{- end}}
          envFrom:
            - configMapRef:
                name: {{ template "proteus.fullname" . }}-config
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.credentials }}
                  key: REDIS_PASSWORD
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 9100
              name: metrics
              protocol: TCP
          {{- with .Values.watchdog.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.watchdog.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.watchdog.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}