---
{{- if .Values.solaredge.web.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "proteus.fullname" . }}-solaredge-web
  labels:
    {{- include "proteus.labels" . | nindent 4 }}
spec:
  {{- with .Values.solaredge.web.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames: {{ .Values.solaredge.web.httpRoute.hostnames | toYaml | nindent 4 }}
  rules:
  - backendRefs:
    - name: {{ include "proteus.fullname" . }}-solaredge-web
      port: 8888
{{- end }}
