---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "proteus.fullname" . }}-solaredge-web
  labels:
    {{- include "proteus.labels" . | nindent 4 }}
spec:
  ports:
    - name: web
      port: 8888
      targetPort: web
  selector:
    app.kubernetes.io/name: {{ template "proteus.fullname" . }}
    app.kubernetes.io/component: solaredge-web